name: Auto Clean Commit

on:
  schedule:                # 在每周二和周五国际凌晨1点执行
    - cron: '0 1 * * 2,5'  # Runs at 01:00 UTC on Tue and Fri.
  workflow_dispatch:

jobs:
  Clean:
    runs-on: ubuntu-latest
    timeout-minutes: 5     #The time for waiting timeout.(等待超时时间)

    steps:
    - name: Clean Cancelled/skipped runs
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const cancelled = await github.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            per_page: 100,
            repo: context.repo.repo,
            status: 'cancelled',
          });

          const skipped = await github.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            per_page: 100,
            repo: context.repo.repo,
            status: 'skipped',
          });

          for (const response of [cancelled, skipped]) {
            for (const run of response.data.workflow_runs) {
              console.log(`Run id ${run.id} of '${run.name}' is a cancelled/skipped run. Deleting...`);
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
          }

    - name: Clean runs older than 3 days
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const days_to_expiration = 3;
          const ms_in_day = 86400000;
          const now = Date.now();
          const pages = 10;
          
          //填入需要清理的workflows文件。
          //Fill in your workflows file which to be cleaned.
          const workflows = [
            'AutoWake.yml',
            'AutoClean.yml'
          ]

          let runs_to_delete = [];

          for (const workflow of workflows) {
            for (let page = 0; page < pages; page += 1) {
              let response = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                page: page,
                per_page: 100,
                repo: context.repo.repo,
                workflow_id: workflow
              });

              if (response.data.workflow_runs.length > 0) {
                for (const run of response.data.workflow_runs) {
                  if (now - Date.parse(run.created_at) > ms_in_day * days_to_expiration) {
                    runs_to_delete.push([run.id, run.name]);
                  }
                }
              }
            }
          }

          for (const run of runs_to_delete) {
            console.log(`Run id ${run[0]} of '${run[1]}' is older than ${days_to_expiration} days. Deleting...`);
            try {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run[0]
              });
            } catch (error) {
              // ignore errors
            }
          }
